### ISSUE TITLE
Change copy to clipboard position

### ISSUE THREAD

**Issue by RajMhatre20** [RajMhatre20/color-generator#1]
Currently, if someone clicks on the shade or tint of the color then "copied to clickboard" text is shown in the color container itself.

![image](https://user-images.githubusercontent.com/68785723/135972275-3134bc11-1ecc-48ef-9cdb-0dd6f86c7ef6.png)

instead of this "copied to clipboard" should be shown in the upper right corner of the page.

**Comment by mkim219** [comment]
Hi, I would like to work this issue! Can you assign me?

**Comment by RajMhatre20** [comment]
Go ahead @mkim219

**Comment by RajMhatre20** [comment]
if you want you can also make a separate component for it

**Comment by mkim219** [comment]
Hi, can you take a look PR that I created?

**Comment by RajMhatre20** [comment]
Hi @mkim219, I looked at your PR and had some changes requested.

**Comment by mkim219** [comment]
HI @RajMhatre20, I have fixed issue that you mentioned on PR! Please review and confirm!
